set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleteregion', @id, '', 'Delete Region', 'delete_region', 2);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleteagency', @id, '', 'Delete Agency', 'delete_agency', 5);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleteteam', @id, '', 'Delete Team', 'delete_team', 11);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleteremployee', @id, '', 'Delete Employee', 'delete_employee', 8);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deletepartner', @id, '', 'Delete Partner', 'delete_partner', 2);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
set @id = (select max(id) + 1 from permissions);
INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleterole', @id, '', 'Delete Role', 'delete_role', 17);
INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
--set @id = (select max(id) + 1 from permissions);
--INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deletecontract', @id, '', 'Delete Contract', 'delete_contract', 20);
--INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);
--set @id = (select max(id) + 1 from permissions);
--INSERT INTO permissions (id, flag, display_menu, display_order, icon, name, permission, parent_id) VALUES (@id, 'ACTIVE', '/deleteclient', @id, '', 'Delete Client', 'delete_client', 25);
--INSERT INTO roles_permissions (role_id,permission_id) VALUES (1, @id);